name: Track&Train Docker CI

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop
      - 'feat/*'
jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installer jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Récupérer la version actuelle depuis package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log version actuelle
        run: |
          echo "La version actuelle extraite de package.json est : ${{ env.VERSION }}"

      - name: Incrémenter la version en fonction de la branche source de la PR
        id: increment_version
        run: |
          VERSION=${{ env.VERSION }}
          BRANCH_NAME="${GITHUB_HEAD_REF}"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          case $BRANCH_NAME in
            feat/*)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            fix/*)
              PATCH=$((PATCH + 1))
              ;;
            *"breaking change"*)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            *)
              echo "Aucun changement sur la version"
              ;;
          esac

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Mettre à jour la version dans package.json
        id: version
        run: |
          jq --arg version "${{ env.VERSION }}" '.version = $version' package.json > tmp.json && mv tmp.json package.json
          echo "version=${{ env.VERSION }}" >> $GITHUB_OUTPUT

      - name: Commit and push the updated package.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "Update version to ${{ env.VERSION }}"
          git push origin ${{ github.ref }}

  setup-docker-tag:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Définir le tag Docker en fonction de la branche de destination
        id: set-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "tag=pre-prod" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi

  build-and-deploy-image:
    needs: [versioning, setup-docker-tag]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Vérifier la version
        run: |
          echo "Version: ${{ needs.versioning.outputs.version }}"

      - name: Valider le tag généré
        run: |
          TAG="${{ needs.setup-docker-tag.outputs.docker_tag }}"
          if [[ ! "$TAG" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
            echo "Invalid tag format: $TAG"
            exit 1
          fi

      - name: Connexion à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Activer Buildx
        uses: docker/setup-buildx-action@v2

      - name: Construire et pousser l'image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ghcr.io/track-train/front:${{ needs.versioning.outputs.version }}
            ghcr.io/track-train/front:latest
            ghcr.io/track-train/front:${{ needs.setup-docker-tag.outputs.docker_tag }}

# add test job waiting test
